import Footer from './components/Footer';
import Nav from './components/Nav';
import './global.css';

import { ChakraProvider } from '@chakra-ui/react';

export const metadata = {
  title: 'Welcome to org',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        {' '}
        <Nav></Nav>
        {children} <Footer />
      </body>
    </html>
  );
}
